spring:
  application:
    name: api-mydrafts
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}/${MONGO_DB}?retryWrites=true&w=majority
tmdb:
  language: pt-BR
  api-key: ${API_KEY}
  api-url: https://api.themoviedb.org/3
  imgs-url: https://image.tmdb.org/t/p/original
