spring:
  application:
    name: api-mydrafts
  data:
    mongodb:
      uri: ${MONGO_URI}
server:
  port: ${PORT:8080}
tmdb:
  language: pt-BR
  key: ${API_KEY}
  host: https://api.themoviedb.org/3
  image: https://image.tmdb.org/t/p/original
secret:
  jwt: ${SECRET_JWT}
